name: PrisonGame
version: ${version}
softdepend:
  - CustomBansPlus
depend:
  - LuckPerms
  - LibsDisguises
main: prisongame.prisongame.PrisonGame
api-version: "1.20"
libraries:
  - net.dv8tion:JDA:5.0.0-beta.18
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.20
  - org.jetbrains.kotlin:kotlin-reflect:1.9.20
commands:
  link:
    description: Link your Minecraft & Discord accounts.
  unlink:
    description: Unlink your Minecraft & Discord accounts.
  gangchat:
    description: Talk to your gang.
    aliases: gc
    usage: /gc (message)
  gangs:
    description: Manage gangs.
    aliases: gang
    usage: /gangs help
  balance:
    description: View balance and leaderboard.
    usage: /balance (leaderboard/view) [player]
  debug:
    description: Debug command
    usage: /debug
    permission: pbb.debug
  season:
    description: Begin a new season.
    usage: /season
    permission: pbb.season
  vanish:
    description: Hide from players.
    usage: /vanish
    permission: pbb.vanish
    aliases: /v
  enderchest:
    description: Inspect/veiw ender chest of provided player.
    usage: /enderchest <inspect/view> (player)
    permission: pbb.enderchest
    aliases: /ec
  pbbreload:
    description: Reloads configuration.
    usage: /pbbreload
    permission: pbb.reload
  rules:
    description: Rules.
    usage: /rules
  warden:
    description: Warden-Based commands.
    usage: /<command>
  resign:
    description: Clears inv and set your rank to prisoner.
    usage: /<command>
  pbsettings:
    description: setting
    usage: /<command>
  hard:
    description: Enables HARD mode.
    usage: /<command>
  normal:
    description: Disables HARD mode.
    usage: /<command>
  rstascen:
    description: Removes all your ascension perks.
    usage: /<command>
  builder:
    permission: pbb.builder
    description: Opens a gui of all prison maps and builder tools.
    usage: /<command>
  nerdcheatcommand:
    permission: pbb.cheats
    description: Gives the player 1000.
    usage: /<command>
  rstmoney:
    permission: pbb.cheats
    description: Resets the player provided
    usage: /<command> <player>
  pay:
    description: Pays the given player the amount provided.
    usage: /<command> <player> <money>
  setmoney:
    permission: pbb.cheat
    description: Sets the money of given player.
    usage: /<command> <player>
  tc:
    aliases: teamchat
    description: Resign from any role your currently in and puts you as prisoner.
    usage: /<command>
  disc:
    aliases: discord
    description: Join the offical PrisonButBad discord server.
    usage: /<command>
  accept:
    description: Accept last role requested by current warden.
    usage: /<command>
  hello:
    description: Say hello and server/credit stats!
    usage: /<command>