name: PrisonGame
version: ${project.version}
softdepend:
  - CustomBansPlus
depend:
  - LuckPerms
  - LibsDisguises
main: prisongame.prisongame.PrisonGame
api-version: "1.20"
libraries:
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.20
commands:
  balance:
    description: View balance and leaderboard.
    usage: /balance (leaderboard/view) [player]
  debug:
    description: Debug command
    usage: /debug
    permission: pbb.debug
  season:
    description: Begin a new season.
    usage: /season
    permission: pbb.season
  vanish:
    description: Hide from players.
    usage: /vanish
    permission: pbb.vanish
    aliases: /v
  enderchest:
    description: Inspect/clear ender chests.
    usage: /enderchest <inspect/view> (player)
    permission: pbb.enderchest
    aliases: /ec
  pbbreload:
    description: Reloads configuration.
    usage: /pbbreload
    permission: pbb.reload
  rules:
    description: Rules.
    usage: /rules
  warden:
    description: Warden-Based commands.
    usage: /<command>
  resign:
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  pbsettings:
    description: setting
    usage: /<command>
  hard:
    description: Enables HARD mode.
    usage: /<command>
  normal:
    description: Disables HARD mode.
    usage: /<command>
  rstascen:
    description: Removes all your ascension perks.
    usage: /<command>
  builder:
    permission: penis.mute
    description: build menu
    usage: /<command>
  nerdcheatcommand:
    permission: pbb.cheats
    description: gives 1000 dollahs
    usage: /<command>
  rstmoney:
    permission: pbb.cheats
    description: gives 0 dollahs
    usage: /<command> <player>
  pay:
    description: gib de monah
    usage: /<command> <player> <money>
  setmoney:
    permission: pbb.set
    description: unmute de playah
    usage: /<command> <player>
  tc:
    aliases: teamchat
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  disc:
    aliases: discord
    description: Resign from your current position/Rejoin from prisoner.
    usage: /<command>
  accept:
    description: Accept a job.
    usage: /<command>
  hello:
    description: Hi!
    usage: /<command>