name: PrisonGame
version: ${version}
softdepend:
  - CustomBansPlus
depend:
  - LuckPerms
  - LibsDisguises
main: prisongame.prisongame.PrisonGame
api-version: "1.20"
libraries:
  - net.dv8tion:JDA:5.0.0-beta.18
  - org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.9.20
  - org.jetbrains.kotlin:kotlin-reflect:1.9.20
commands:
  link:
    description: Link your Minecraft & Discord accounts.
  unlink:
    description: Unlink your Minecraft & Discord accounts.
  gangchat:
    description: Talk to your gang.
    aliases: gc
    usage: /gc (message)
  gangs:
    description: Manage gangs.
    aliases: gang
    usage: /gangs help
  balance:
    description: View balance of players and leaderboard.
    usage: /balance (leaderboard/view) [player]
  debug:
    description: Debug command
    usage: /debug
    permission: pbb.debug
  season:
    description: Begin a new season.
    usage: /season
    permission: pbb.season
  vanish:
    description: Removes you from tab visually to all players.
    usage: /vanish
    permission: pbb.vanish
    aliases: /v
  enderchest:
    description: inspects/veiws a player's ender chest.
    usage: /enderchest <inspect/view> (player)
    permission: pbb.enderchest
    aliases: /ec
  pbbreload:
    description: Reloads configuration.
    usage: /pbbreload
    permission: pbb.reload
  rules:
    description: Rules.
    usage: /rules
  warden:
    description: Warden-Based commands.
    usage: /<command>
  resign:
    description: Resign from your current position.
    usage: /<command>
  pbsettings:
    description: setting
    usage: /<command>
  hard:
    description: Enables HARD mode.
    usage: /<command>
  normal:
    description: Disables HARD mode.
    usage: /<command>
  rstascen:
    description: Removes all your ascension perks.
    usage: /<command>
  builder:
    permission: pbb.builder
    description: build menu
    usage: /<command>
  nerdcheatcommand:
    permission: pbb.cheats
    description: gives 1000 dollahs
    usage: /<command>
  rstmoney:
    permission: pbb.cheats
    description: Resets the player balance to 0.
    usage: /<command> <player>
  pay:
    description: pays another player.
    usage: /<command> <player> <money>
  setmoney:
    permission: pbb.cheat
    description: Set a players balance.
    usage: /<command> <player>
  tc:
    aliases: teamchat
    description: Speak in whatever team your on.
    usage: /<command>
  disc:
    aliases: discord
    description: Join the Discord server.
    usage: /<command>
  accept:
    description: Accepts the last requested role from current warden.
    usage: /<command>
  hello:
    description: Gets server,map,credits, and says hello.
    usage: /<command>